spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

spring:
  datasource:
    url: jdbc:postgresql://cloud-apps-databases.c6rozbroiykj.us-east-1.rds.amazonaws.com/confluence_exporter
    username: atlassianapps
    password: KjSM4VMn

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB


server:
  port: 8088
  servlet:
    session.tracking-modes: COOKIE
    context-path: /confluenceexporter

addon:
  key: com.miniorange.exporter.confluenceexporter
  base-url: https://cloudapps.xecurify.com

logging:
  file.name: /var/log/atlassianapps/confluence-exporter/debug.log

  #  after filling max-size in one file, the file will be automatically rolled
  level.com.miniorange.exporter: INFO
  # this pattern is responsible to roll the log file every day
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: /var/log/atlassianapps/confluence-exporter/debug-%d{yyyy-MM-dd}.%i.log

logging.level.com.atlassian.connect.spring: INFO

spring.security.user.name: miniOexporter
spring.security.user.password: atlassianCloudMiniOexporter#25050
